# Generated by Django 5.1.1 on 2024-11-29 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gotmail_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
