# Generated by Django 5.1.1 on 2024-11-29 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gotmail_service", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="auto_reply_from_email",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="notification_email",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="notification_push",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="signature",
        ),
    ]
