# Generated by Django 5.1.1 on 2024-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gotmail_service", "0003_remove_usersettings_auto_reply_from_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="mailbox",
            field=models.CharField(
                choices=[
                    ("inbox", "Inbox"),
                    ("sent", "Sent"),
                    ("draft", "Draft"),
                    ("trash", "Trash"),
                ],
                default="inbox",
                max_length=20,
            ),
        ),
    ]
