# Generated by Django 5.1.1 on 2024-12-02 00:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gotmail_service", "0004_email_mailbox"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="mailbox",
        ),
        migrations.RemoveField(
            model_name="email",
            name="status",
        ),
    ]
