# Generated by Django 5.1.1 on 2024-12-03 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gotmail_service", "0007_smsverification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SMSVerification",
        ),
    ]
