# Generated by Django 5.1.1 on 2024-12-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gotmail_service", "0008_delete_smsverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
