# Generated by Django 5.1.1 on 2024-12-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gotmail_service", "0009_user_password_reset_expires_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="password_reset_expires",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="password_reset_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="two_factor_secret",
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
